1. Create a class Employee and then do the following

In [1]:
class Employee:
    numberOfEmployees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.numberOfEmployees+=1


def averagesalary(employee):
    total = sum(e.salary for e in employee)
    average = total / len(employee)
    return average

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        Employee.__init__(self,name, family, salary, department)

print("Employee 1: ")
employee1 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Employee 2: ")
employee2 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Full Time Employee 1: ")
employee3 = FulltimeEmployee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("")
print("Number of employees: ",Employee.numberOfEmployees)
listofEmployees = [employee1, employee2]
avgsalary = averagesalary(listofEmployees)
print("Avg salary is :", avgsalary)

Employee 1: 
Enter name: Mythreya
Family Members: 4
Employee Salary: 89000
Employee Department: CS
Employee 2: 
Enter name: Mythu
Family Members: 4
Employee Salary: 99000
Employee Department: IT
Full Time Employee 1: 
Enter name: Grandhe
Family Members: 6
Employee Salary: 90000
Employee Department: CS

Number of employees:  3
Avg salary is : 94000.0


2. Numpy
Using NumPy create random vector of size 20 having only float in the range 1-20.
Then reshape the array to 4 by 5
Then replace the max in each row by 0 (axis=1)


In [2]:
import numpy

random_vector = numpy.random.uniform(1, 20, 20)
print(random_vector)
print("")
print("")
reshaped_array = random_vector.reshape(4, 5)
print("")
print("")
print(reshaped_array)
reshaped_array[numpy.arange(4), numpy.argmax(reshaped_array, axis=1)] = 0
print("")
print("")
print(reshaped_array)

[ 9.69090139  5.15372359  7.34888505 16.0579306  17.30212624 17.42600726
 11.69748367 18.32136265  4.58218645 17.39346205  3.98600997  8.28798299
 16.53242394 13.70965634 16.53950528 17.56115827 17.3208168   9.94684761
  3.32546365  1.13605918]




[[ 9.69090139  5.15372359  7.34888505 16.0579306  17.30212624]
 [17.42600726 11.69748367 18.32136265  4.58218645 17.39346205]
 [ 3.98600997  8.28798299 16.53242394 13.70965634 16.53950528]
 [17.56115827 17.3208168   9.94684761  3.32546365  1.13605918]]


[[ 9.69090139  5.15372359  7.34888505 16.0579306   0.        ]
 [17.42600726 11.69748367  0.          4.58218645 17.39346205]
 [ 3.98600997  8.28798299 16.53242394 13.70965634  0.        ]
 [ 0.         17.3208168   9.94684761  3.32546365  1.13605918]]
